name: expense_tracker
description: A Flutter Application which can be used to store users' expense data remotely.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: 7.1.1
  intl: ^0.18.0
  riverpod_annotation: 2.1.1
  cupertino_icons: ^1.0.2
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  flutter_spinkit: ^5.2.0
  firebase_ui_firestore: ^1.5.2
  firebase_ui_auth: ^1.4.2
  datetime_picker_formfield_new: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf